import '/styles/style.css'
import '/styles/components/header.css'
import '/styles/components/MobileMenu.css'
import '/styles/components/hero.css'
import '/styles/components/about.css'
import '/styles/components/classes.css'
import '/styles/components/offers.css'
import '/styles/components/memberships.css'
import '/styles/components/testimonials.css'
import '/styles/components/subscribe.css'
import '/styles/components/contact.css'
import '/styles/components/footer.css'
import '/styles/utility.css'

import '/src/mobileMenu'